---
title: "bbc_style"
author: "Kadek Adit Wiryadana"
date: "`r Sys.Date()`"
output: html_document
---

### Install all library
```{r}
if(!require(pacman))install.packages("pacman")

pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')
```

Install BBplot
```{r}
devtools::install_github('bbc/bbplot')
```

### Example
```{r}
#Data for chart from gapminder package
line_df <- gapminder %>%
  filter(country == "Indonesia") 

#Make plot
line <- ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#1380A1", size = 1) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  labs(title="Living longer",
       subtitle = "Life expectancy in Indonesia 1952-2007")
line

line_bbc <- ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#1380A1", size = 1) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  labs(title="Living longer",
       subtitle = "Life expectancy in Indonesia 1952-2007")
line_bbc
```

